import pycountry
import holidayapi
import csv

un_countries = [
    {"name": 'Afghanistan'},
    {"name": 'Albania'},
    {"name": 'Algeria'},
    {"name": 'Andorra'},
    {"name": 'Angola'},
    {"name": 'Antigua and Barbuda'},
    {"name": 'Argentina'},
    {"name": 'Armenia'},
    {"name": 'Australia'},
    {"name": 'Austria'},
    {"name": 'Azerbaijan'},
    {"name": 'Bahamas'},
    {"name": 'Bahrain'},
    {"name": 'Bangladesh'},
    {"name": 'Barbados'},
    {"name": 'Belarus'},
    {"name": 'Belgium'},
    {"name": 'Belize'},
    {"name": 'Benin'},
    {"name": 'Bhutan'},
    {"name": 'Bolivia, Plurinational State of', "country_small_name": "Bolivia"},
    {"name": 'Bosnia and Herzegovina'},
    {"name": 'Botswana'},
    {"name": 'Brazil'},
    {"name": 'Brunei Darussalam', "country_small_name": 'Brunei'},
    {"name": 'Bulgaria'},
    {"name": 'Burkina Faso'},
    {"name": 'Burundi'},
    {"name": 'Cabo Verde'},
    {"name": 'Cambodia'},
    {"name": 'Cameroon'},
    {"name": 'Canada'},
    {"name": 'Central African Republic'},
    {"name": 'Chad'},
    {"name": 'Chile'},
    {"name": 'China'},
    {"name": 'Colombia'},
    {"name": 'Comoros'},
    {"name": 'Congo'},
    {"name": 'Congo, The Democratic Republic of the', "country_small_name": 'DR Congo'},
    {"name": 'Costa Rica'},
    {"name": 'Côte D\'Ivoire'},
    {"name": 'Croatia'},
    {"name": 'Cuba'},
    {"name": 'Cyprus'},
    {"name": 'Czechia'},
    {"name": 'Czechia'},
    {"name": 'Denmark'},
    {"name": 'Djibouti'},
    {"name": 'Dominica'},
    {"name": 'Dominican Republic'},
    {"name": 'Ecuador'},
    {"name": 'Egypt'},
    {"name": 'El Salvador'},
    {"name": 'Equatorial Guinea'},
    {"name": 'Eritrea'},
    {"name": 'Estonia'},
    {"name": 'Eswatini'},
    {"name": 'Ethiopia'},
    {"name": 'Fiji'},
    {"name": 'Finland'},
    {"name": 'France'},
    {"name": 'Gabon'},
    {"name": 'Gambia'},
    {"name": 'Georgia'},
    {"name": 'Germany'},
    {"name": 'Ghana'},
    {"name": 'Greece'},
    {"name": 'Grenada'},
    {"name": 'Guatemala'},
    {"name": 'Guinea'},
    {"name": 'Guinea-Bissau'},
    {"name": 'Guyana'},
    {"name": 'Haiti'},
    {"name": 'Honduras'},
    {"name": 'Hungary'},
    {"name": 'Iceland'},
    {"name": 'India'},
    {"name": 'Indonesia'},
    {"name": 'Iran, Islamic Republic of', "country_small_name": "Iran"},
    {"name": 'Iraq'},
    {"name": 'Ireland'},
    {"name": 'Israel'},
    {"name": 'Italy'},
    {"name": 'Jamaica'},
    {"name": 'Japan'},
    {"name": 'Jordan'},
    {"name": 'Kazakhstan'},
    {"name": 'Kenya'},
    {"name": 'Kiribati'},
    {"name": 'Kuwait'},
    {"name": 'Kyrgyzstan'},
    {"name": 'Lao People\'s Democratic Republic', "country_small_name": 'Laos'},
    {"name": 'Latvia'},
    {"name": 'Lebanon'},
    {"name": 'Lesotho'},
    {"name": 'Liberia'},
    {"name": 'Libya'},
    {"name": 'Liechtenstein'},
    {"name": 'Lithuania'},
    {"name": 'Luxembourg'},
    {"name": 'Madagascar'},
    {"name": 'Malawi'},
    {"name": 'Malaysia'},
    {"name": 'Maldives'},
    {"name": 'Mali'},
    {"name": 'Malta'},
    {"name": 'Marshall Islands'},
    {"name": 'Mauritania'},
    {"name": 'Mauritius'},
    {"name": 'Mexico'},
    {"name": 'Micronesia, Federated States of', "country_small_name": "Micronesia"},
    {"name": 'Moldova, Republic of', "country_small_name": "Moldova"},
    {"name": 'Monaco'},
    {"name": 'Mongolia'},
    {"name": 'Montenegro'},
    {"name": 'Morocco'},
    {"name": 'Mozambique'},
    {"name": 'Myanmar'},
    {"name": 'Namibia'},
    {"name": 'Nauru'},
    {"name": 'Nepal'},
    {"name": 'Netherlands'},
    {"name": 'New Zealand'},
    {"name": 'Nicaragua'},
    {"name": 'Niger'},
    {"name": 'Nigeria'},
    {"name": 'Korea, Democratic People\'s Republic of', "country_small_name": 'North Korea', },
    {"name": 'North Macedonia'},
    {"name": 'Norway'},
    {"name": 'Oman'},
    {"name": 'Pakistan'},
    {"name": 'Palau'},
    {"name": 'Panama'},
    {"name": 'Papua New Guinea'},
    {"name": 'Paraguay'},
    {"name": 'Peru'},
    {"name": 'Philippines'},
    {"name": 'Poland'},
    {"name": 'Portugal'},
    {"name": 'Qatar'},
    {"name": 'Romania'},
    {"name": 'Russian Federation', "country_small_name": "Russia"},
    {"name": 'Rwanda'},
    {"name": 'Saint Kitts and Nevis'},
    {"name": 'Saint Lucia'},
    {"name": 'Saint Vincent and the Grenadines'},
    {"name": 'Samoa'},
    {"name": 'San Marino'},
    {"name": 'Sao Tome and Principe'},
    {"name": 'Saudi Arabia'},
    {"name": 'Senegal'},
    {"name": 'Serbia'},
    {"name": 'Seychelles'},
    {"name": 'Sierra Leone'},
    {"name": 'Singapore'},
    {"name": 'Slovakia'},
    {"name": 'Slovenia'},
    {"name": 'Solomon Islands'},
    {"name": 'Somalia'},
    {"name": 'South Africa'},
    {"name": 'Korea, Republic of', "country_small_name": "South Korea"},
    {"name": 'South Sudan'},
    {"name": 'Spain'},
    {"name": 'Sri Lanka'},
    {"name": 'Sudan'},
    {"name": 'Suriname'},
    {"name": 'Sweden'},
    {"name": 'Switzerland'},
    {"name": 'Syrian Arab Republic', "country_small_name": 'Syria'},
    {"name": 'Tajikistan'},
    {"name": 'Thailand'},
    {"name": 'Timor-Leste'},
    {"name": 'Togo'},
    {"name": 'Tonga'},
    {"name": 'Trinidad and Tobago'},
    {"name": 'Tunisia'},
    {"name": 'Turkmenistan'},
    {"name": 'Tuvalu'},
    {"name": 'Uganda'},
    {"name": 'Ukraine'},
    {"name": 'United Arab Emirates'},
    {"name": 'United Kingdom'},
    {"name": 'Tanzania, United Republic of', "country_small_name": "Tanzania"},
    {"name": 'USA'},
    {"name": 'Uruguay'},
    {"name": 'Uzbekistan'},
    {"name": 'Vanuatu'},
    {"name": 'Venezuela, Bolivarian Republic of', "country_small_name": "Venezuela"},
    {"name": 'Viet Nam'},
    {"name": 'Yemen'},
    {"name": 'Zambia'},
    {"name": 'Zimbabwe'}
]

countries = []
for country in un_countries:
    pycountry_item = pycountry.countries.search_fuzzy(country["name"])[0]
    countries.append({
        "name": pycountry_item.name,
        "country_small_name": country.get("country_small_name"),
        "code": pycountry_item.alpha_2,
        "flag": pycountry_item.flag
    })

calendar = []
holiday_api_key = '647bed32-c177-4972-9bd6-306c692425d5'
hapi = holidayapi.v1(holiday_api_key)

for country in countries:
    print(country["name"])
    pyc = pycountry.countries.get(alpha_2 = country["code"])
    holidays = hapi.holidays({"country": country["code"].upper(), 'year': '2022'})['holidays']
    for holiday in holidays:
        if holiday['public'] and (holiday['date'] == holiday['observed']):
            calendar.append({"date": holiday['date'], "name": holiday['name'], "country": pyc.name, "country_small_name": country.get("country_small_name"), "flag": pyc.flag})

with open('calendar.csv', 'w', newline='') as csvfile:
    fieldnames = ['date', 'name', 'country', 'country_small_name', 'flag']
    writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
    writer.writeheader()
    for day in calendar:
        writer.writerow({"date": day['date'], "name": day['name'], "country": day['country'], "country_small_name": day["country_small_name"], "flag": day['flag']})
